// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';

export function AddNode(arg1:internal.Node):Promise<void>;

export function BatchTestConnections(arg1:string,arg2:string):Promise<Record<string, internal.NodeStatus>>;

export function DeleteCredential(arg1:string,arg2:string):Promise<void>;

export function DeleteNode(arg1:string):Promise<void>;

export function GetNode(arg1:string):Promise<internal.Node>;

export function GetNodes():Promise<Array<internal.Node>>;

export function GetTopology():Promise<internal.TopologyData>;

export function Greet(arg1:string):Promise<string>;

export function HasStoredCredential(arg1:string,arg2:string):Promise<boolean>;

export function HasStoredKeyPassphrase(arg1:string):Promise<boolean>;

export function SaveCredential(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function SaveKeyPassphrase(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SelectKeyFile():Promise<string>;

export function TestConnectionWithCredentials(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<internal.NodeStatus>;

export function TestNodeConnection(arg1:string,arg2:string,arg3:string):Promise<internal.NodeStatus>;

export function UpdateNode(arg1:internal.Node):Promise<void>;
