// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNode(arg1) {
  return window['go']['main']['App']['AddNode'](arg1);
}

export function BatchTestConnections(arg1, arg2) {
  return window['go']['main']['App']['BatchTestConnections'](arg1, arg2);
}

export function DeleteCredential(arg1, arg2) {
  return window['go']['main']['App']['DeleteCredential'](arg1, arg2);
}

export function DeleteNode(arg1) {
  return window['go']['main']['App']['DeleteNode'](arg1);
}

export function GetNode(arg1) {
  return window['go']['main']['App']['GetNode'](arg1);
}

export function GetNodes() {
  return window['go']['main']['App']['GetNodes']();
}

export function GetTopology() {
  return window['go']['main']['App']['GetTopology']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HasStoredCredential(arg1, arg2) {
  return window['go']['main']['App']['HasStoredCredential'](arg1, arg2);
}

export function HasStoredKeyPassphrase(arg1) {
  return window['go']['main']['App']['HasStoredKeyPassphrase'](arg1);
}

export function SaveCredential(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveCredential'](arg1, arg2, arg3, arg4);
}

export function SaveKeyPassphrase(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveKeyPassphrase'](arg1, arg2, arg3);
}

export function SelectKeyFile() {
  return window['go']['main']['App']['SelectKeyFile']();
}

export function TestConnectionWithCredentials(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TestConnectionWithCredentials'](arg1, arg2, arg3, arg4, arg5);
}

export function TestNodeConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestNodeConnection'](arg1, arg2, arg3);
}

export function UpdateNode(arg1) {
  return window['go']['main']['App']['UpdateNode'](arg1);
}
